// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Template__Html$ReasonBlog = require("./Template__Html.bs.js");

function blogPostToListItem(blogPost) {
  return React.createElement("li", {
              key: blogPost.id
            }, React.createElement("p", undefined, React.createElement("a", {
                      href: blogPost.id + ".html"
                    }, blogPost.title), React.createElement("br", undefined), React.createElement("span", undefined, blogPost.date.toDateString())));
}

function Template__BlogIndex(Props) {
  var blogTitle = Props.blogTitle;
  var blogPosts = Props.blogPosts;
  return React.createElement(Template__Html$ReasonBlog.make, {
              title: blogTitle,
              children: null
            }, React.createElement("h1", undefined, blogTitle), React.createElement("ul", undefined, blogPosts.map(blogPostToListItem)));
}

var make = Template__BlogIndex;

exports.blogPostToListItem = blogPostToListItem;
exports.make = make;
/* react Not a pure module */
