// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Template__Html(Props) {
  var title = Props.title;
  var children = Props.children;
  return React.createElement("html", undefined, React.createElement("head", undefined, React.createElement("title", undefined, title)), React.createElement("body", undefined, children));
}

var make = Template__Html;

exports.make = make;
/* react Not a pure module */
