// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Template__Html$ReasonBlog = require("./Template__Html.bs.js");

function blogPostToListItem(blogPost) {
  return React.createElement("p", {
              key: blogPost.id
            }, React.createElement("a", {
                  href: blogPost.id + ".html"
                }, blogPost.title), React.createElement("br", undefined), React.createElement("span", undefined, blogPost.date.toDateString()));
}

function Template__BlogIndex(Props) {
  var blogPosts = Props.blogPosts;
  return React.createElement(Template__Html$ReasonBlog.make, {
              title: "ReScript Blog",
              children: null
            }, React.createElement("p", undefined, React.createElement("a", {
                      href: "about.html"
                    }, "About this blog →")), React.createElement("h1", undefined, "ReScript Blog"), blogPosts.map(blogPostToListItem));
}

var make = Template__BlogIndex;

exports.blogPostToListItem = blogPostToListItem;
exports.make = make;
/* react Not a pure module */
