// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MarkdownIt = require("markdown-it");

var markdownIt = MarkdownIt();

exports.markdownIt = markdownIt;
/* markdownIt Not a pure module */
