// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");

var rootDir = "./content";

var postsDir = "./content/posts";

function toResult(error, items) {
  if (error == null) {
    if (items == null) {
      return /* ReadDirResult */Block.__(1, [/* [] */0]);
    } else {
      return /* ReadDirResult */Block.__(1, [$$Array.to_list(items)]);
    }
  } else {
    return /* ReadDirError */Block.__(0, [error]);
  }
}

function onItems(items) {
  console.log(items);
  return /* () */0;
}

function onDir(error, items) {
  var result = toResult(error, items);
  console.log(result[0]);
  return /* () */0;
}

Fs.readdir(postsDir, onDir);

exports.rootDir = rootDir;
exports.postsDir = postsDir;
exports.toResult = toResult;
exports.onItems = onItems;
exports.onDir = onDir;
/*  Not a pure module */
